#!/usr/bin/env node
/** Pack isolated local elbow-weight edits onto exact published grip-recovery assets.
 * Keeps original rig, actions, textures and protected hand/boot surfaces.
 * This separate experimental packer permits an explicitly mapped elbow weight edit.
 * meshoptimizer 0.24.0, Blender 4.3.2. See validation/ELBOW_CUFF_CANDIDATES_2026-10-03.md.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {MeshoptDecoder} from '../../node_modules/three/examples/jsm/libs/meshopt_decoder.module.js';
const args={};for(let i=2;i<process.argv.length;i+=2)args[process.argv[i].slice(2)]=process.argv[i+1];
if(!args.source||!args.out||!process.env.MODEL_ENCODER)throw Error('Require --source FILE --out DIR and MODEL_ENCODER module path');
const {MeshoptEncoder}=await import(pathToFileURL(process.env.MODEL_ENCODER));await Promise.all([MeshoptDecoder.ready,MeshoptEncoder.ready]);
const source=await fs.readFile(args.source),sourceHash=createHash('sha256').update(source).digest('hex');
const sourceRole=sourceHash==='1865eb66beef6fe492c301779ed4da3fd7b4c771a43756a7bbdcd4bbb0e6b772'?'keeper':'striker';
if(!['1865eb66beef6fe492c301779ed4da3fd7b4c771a43756a7bbdcd4bbb0e6b772','bf3ec0d6e53766c6a8fd7e7a5775087a3886eed752921a906f36497491b3157f'].includes(sourceHash))throw Error('This pass requires exact grip-recovery source assets; do not apply twice');
const jsonLength=source.readUInt32LE(12),doc=JSON.parse(source.subarray(20,20+jsonLength)),bin=source.subarray(28+jsonLength),raw=[];
for(const view of doc.bufferViews){const e=view.extensions?.EXT_meshopt_compression;if(e){const bytes=new Uint8Array(view.byteLength);MeshoptDecoder.decodeGltfBuffer(bytes,e.count,e.byteStride,bin.subarray(e.byteOffset,e.byteOffset+e.byteLength),e.mode,e.filter);raw.push(Buffer.from(bytes));}else raw.push(Buffer.from(bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength)));}
const component={5121:[1,'readUInt8','writeUInt8'],5123:[2,'readUInt16LE','writeUInt16LE'],5125:[4,'readUInt32LE','writeUInt32LE'],5126:[4,'readFloatLE','writeFloatLE']},width={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
function read(id){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],c=component[a.componentType],w=width[a.type],stride=v.byteStride??c[0]*w,b=raw[a.bufferView];return Array.from({length:a.count},(_,i)=>Array.from({length:w},(_,k)=>b[c[1]]((a.byteOffset??0)+i*stride+k*c[0])));}
const edited=new Set();
function write(id,values){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],c=component[a.componentType],w=width[a.type],stride=c[0]*w,b=Buffer.alloc(values.length*stride);for(let i=0;i<values.length;i++)for(let k=0;k<w;k++)b[c[2]](values[i][k],i*stride+k*c[0]);if(b.equals(raw[a.bufferView]))return;raw[a.bufferView]=b;a.count=values.length;a.byteOffset=0;v.byteLength=b.length;delete v.byteStride;edited.add(a.bufferView);if(a.min){a.min=Array.from({length:w},(_,k)=>Math.min(...values.map(v=>v[k])));a.max=Array.from({length:w},(_,k)=>Math.max(...values.map(v=>v[k])));}}

const stats={sourceSha256:sourceHash,role:sourceRole,authoringScriptSha256:createHash('sha256').update(await fs.readFile(new URL(import.meta.url))).digest('hex')};
const primitives=doc.meshes.flatMap(m=>m.primitives).map((p,i)=>({i,material:doc.materials[p.material].name,positions:read(p.attributes.POSITION),normals:read(p.attributes.NORMAL),indices:read(p.indices).flat(),joints:read(p.attributes.JOINTS_0),weights:read(p.attributes.WEIGHTS_0)}));
await fs.mkdir(args.out,{recursive:true});
await fs.writeFile(path.join(args.out,path.basename(args.source,'.glb')+'-rig.json'),JSON.stringify({names:doc.skins[0].joints.map(i=>doc.nodes[i].name),inverseBindMatrices:read(doc.skins[0].inverseBindMatrices)}));
if(args.edits){const edit=JSON.parse(await fs.readFile(args.edits,'utf8'));const parts=doc.meshes.flatMap(m=>m.primitives);for(let i=0;i<parts.length;i++){const p=parts[i];if(edit[i].material!==primitives[i].material||edit[i].positions.length!==primitives[i].positions.length||edit[i].normals.length!==primitives[i].normals.length||![...edit[i].positions,...edit[i].normals].every(v=>v.length===3&&v.every(Number.isFinite)))throw Error('Invalid topology-preserving edit');write(p.attributes.POSITION,edit[i].positions);write(p.attributes.NORMAL,edit[i].normals);if(JSON.stringify(edit[i].positions)!==JSON.stringify(primitives[i].positions)||JSON.stringify(edit[i].normals)!==JSON.stringify(primitives[i].normals))throw Error('Weight-only candidate must preserve positions and normals');if(edit[i].joints.length!==primitives[i].joints.length||edit[i].weights.length!==primitives[i].weights.length)throw Error('Weight topology changed');write(p.attributes.JOINTS_0,edit[i].joints);write(p.attributes.WEIGHTS_0,edit[i].weights);}

}
else await fs.writeFile(path.join(args.out,path.basename(args.source,'.glb')+'-mesh.json'),JSON.stringify(primitives));
const normalViews=new Set(doc.meshes.flatMap(m=>m.primitives.map(p=>doc.accessors[p.attributes.NORMAL].bufferView)));
const positionViews=new Set(doc.meshes.flatMap(m=>m.primitives.map(p=>doc.accessors[p.attributes.POSITION].bufferView)));
const finalRaw=new Map();stats.encodingMaxPositionErrorMm=0;stats.encodingMaxNormalComponentError=0;
function pack(compressed){const d=structuredClone(doc),chunks=[];let offset=0,fallback=0;for(let i=0;i<d.bufferViews.length;i++){const v=d.bufferViews[i],old=doc.bufferViews[i].extensions?.EXT_meshopt_compression;let payload;if(compressed&&old){const count=edited.has(i)?raw[i].length/old.byteStride:old.count;const normal=edited.has(i)&&normalViews.has(i),position=edited.has(i)&&positionViews.has(i),input=normal||position?MeshoptEncoder.encodeFilterExp(new Float32Array(raw[i].buffer,raw[i].byteOffset,raw[i].byteLength/4),count,old.byteStride,normal?12:18,'SharedComponent'):raw[i];payload=edited.has(i)?Buffer.from(MeshoptEncoder.encodeGltfBuffer(input,count,old.byteStride,old.mode)):bin.subarray(old.byteOffset,old.byteOffset+old.byteLength);if(edited.has(i)){const decoded=new Uint8Array(raw[i].length);MeshoptDecoder.decodeGltfBuffer(decoded,count,old.byteStride,payload,old.mode,normal||position?'EXPONENTIAL':'NONE');finalRaw.set(i,Buffer.from(decoded));if(normal||position){const before=new Float32Array(raw[i].buffer,raw[i].byteOffset,raw[i].byteLength/4),after=new Float32Array(decoded.buffer);let error=0;for(let n=0;n<before.length;n++)error=Math.max(error,Math.abs(before[n]-after[n]));if(position)stats.encodingMaxPositionErrorMm=Math.max(stats.encodingMaxPositionErrorMm,error*1000);else stats.encodingMaxNormalComponentError=Math.max(stats.encodingMaxNormalComponentError,error);}}v.extensions={EXT_meshopt_compression:{...old,buffer:0,byteOffset:offset,byteLength:payload.length,count,...(edited.has(i)?{filter:normal||position?'EXPONENTIAL':'NONE'}:{})}};v.buffer=1;v.byteOffset=fallback;fallback+=v.byteLength;}else{payload=finalRaw.get(i)??raw[i];v.buffer=0;v.byteOffset=offset;delete v.extensions;}chunks.push(payload);offset+=payload.length;const pad=(4-offset%4)%4;chunks.push(Buffer.alloc(pad));offset+=pad;}d.buffers=[{byteLength:offset},...(compressed?[{byteLength:fallback}]:[])];if(!compressed){d.extensionsUsed=d.extensionsUsed?.filter(x=>x!=='EXT_meshopt_compression');d.extensionsRequired=d.extensionsRequired?.filter(x=>x!=='EXT_meshopt_compression');}let j=Buffer.from(JSON.stringify(d));j=Buffer.concat([j,Buffer.alloc((4-j.length%4)%4,32)]);const binary=Buffer.concat(chunks),h=Buffer.alloc(20),bh=Buffer.alloc(8);h.write('glTF');h.writeUInt32LE(2,4);h.writeUInt32LE(28+j.length+binary.length,8);h.writeUInt32LE(j.length,12);h.write('JSON',16);bh.writeUInt32LE(binary.length);bh.write('BIN\0',4);return Buffer.concat([h,j,bh,binary]);}

const name=path.basename(args.source,'.glb'),candidate=pack(true);stats.bytes=candidate.length;stats.triangles=doc.meshes.flatMap(m=>m.primitives).reduce((n,p)=>n+doc.accessors[p.indices].count/3,0);if(stats.bytes>450000||stats.triangles>18000)throw Error('Budget exceeded');await fs.writeFile(path.join(args.out,name+'.glb'),candidate);await fs.writeFile(path.join(args.out,name+'-decoded.glb'),pack(false));await fs.writeFile(path.join(args.out,name+'-stats.json'),JSON.stringify(stats,null,2));console.log({...stats,hemBoundaryMap:stats.hemBoundaryMap?.length});
