#!/usr/bin/env node
/** Pack topology-preserving Blender body edits onto exact published v17 assets.
 * Keeps original rig, actions, textures, weights and protected hand/boot surfaces.
 * Optional hem replaces only the old shorts trim; metadata maps all new vertices.
 * meshoptimizer 0.24.0, Blender 4.3.2. See BODY_CLOTH_REFINEMENT.md.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {MeshoptDecoder} from '../../node_modules/three/examples/jsm/libs/meshopt_decoder.module.js';
const args={};for(let i=2;i<process.argv.length;i+=2)args[process.argv[i].slice(2)]=process.argv[i+1];
if(!args.source||!args.out||!process.env.MODEL_ENCODER)throw Error('Require --source FILE --out DIR and MODEL_ENCODER module path');
const {MeshoptEncoder}=await import(pathToFileURL(process.env.MODEL_ENCODER));await Promise.all([MeshoptDecoder.ready,MeshoptEncoder.ready]);
const source=await fs.readFile(args.source),sourceHash=createHash('sha256').update(source).digest('hex');
const sourceRole=sourceHash==='af13951cda7f7655e98eed9fa5cdb0b903b73379f9e7260f5d8e67089fafbf19'?'keeper':'striker';
if(!['af13951cda7f7655e98eed9fa5cdb0b903b73379f9e7260f5d8e67089fafbf19','e0b3eb06d09d80135827c5f5e7e58ab26778a5dc0b8c3333be48a704603bfc3d'].includes(sourceHash))throw Error('This pass requires exact v17 source assets; do not apply twice');
const jsonLength=source.readUInt32LE(12),doc=JSON.parse(source.subarray(20,20+jsonLength)),bin=source.subarray(28+jsonLength),raw=[];
for(const view of doc.bufferViews){const e=view.extensions?.EXT_meshopt_compression;if(e){const bytes=new Uint8Array(view.byteLength);MeshoptDecoder.decodeGltfBuffer(bytes,e.count,e.byteStride,bin.subarray(e.byteOffset,e.byteOffset+e.byteLength),e.mode,e.filter);raw.push(Buffer.from(bytes));}else raw.push(Buffer.from(bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength)));}
const component={5121:[1,'readUInt8','writeUInt8'],5123:[2,'readUInt16LE','writeUInt16LE'],5125:[4,'readUInt32LE','writeUInt32LE'],5126:[4,'readFloatLE','writeFloatLE']},width={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
function read(id){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],c=component[a.componentType],w=width[a.type],stride=v.byteStride??c[0]*w,b=raw[a.bufferView];return Array.from({length:a.count},(_,i)=>Array.from({length:w},(_,k)=>b[c[1]]((a.byteOffset??0)+i*stride+k*c[0])));}
const edited=new Set();
function write(id,values){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],c=component[a.componentType],w=width[a.type],stride=c[0]*w,b=Buffer.alloc(values.length*stride);for(let i=0;i<values.length;i++)for(let k=0;k<w;k++)b[c[2]](values[i][k],i*stride+k*c[0]);if(b.equals(raw[a.bufferView]))return;raw[a.bufferView]=b;a.count=values.length;a.byteOffset=0;v.byteLength=b.length;delete v.byteStride;edited.add(a.bufferView);if(a.min){a.min=Array.from({length:w},(_,k)=>Math.min(...values.map(v=>v[k])));a.max=Array.from({length:w},(_,k)=>Math.max(...values.map(v=>v[k])));}}

const stats={sourceSha256:sourceHash,role:sourceRole};
const primitives=doc.meshes.flatMap(m=>m.primitives).map((p,i)=>({i,material:doc.materials[p.material].name,positions:read(p.attributes.POSITION),normals:read(p.attributes.NORMAL),indices:read(p.indices).flat(),joints:read(p.attributes.JOINTS_0),weights:read(p.attributes.WEIGHTS_0)}));
await fs.mkdir(args.out,{recursive:true});
if(args.edits){const edit=JSON.parse(await fs.readFile(args.edits,'utf8'));const parts=doc.meshes.flatMap(m=>m.primitives);for(let i=0;i<parts.length;i++){const p=parts[i];write(p.attributes.POSITION,edit[i].positions);write(p.attributes.NORMAL,edit[i].normals);}
 if(args.hem==='true'){
 const si=primitives.findIndex(p=>p.material.startsWith('Skin')),ki=primitives.findIndex(p=>p.material==='Shorts'),bi=primitives.findIndex(p=>p.material==='Boots');
 const key=v=>v.map(n=>Math.round(n*1e5)).join(',');const skin=new Map(primitives[si].positions.map((v,i)=>[key(v),i]));const p=parts[ki],original=primitives[ki],data=Object.fromEntries(Object.entries(p.attributes).map(([name,id])=>[name,read(id)])),idx=read(p.indices).flat(),edges=new Map();
 for(let n=0;n<idx.length;n+=3)for(let k=0;k<3;k++){const a=idx[n+k],b=idx[n+(k+1)%3],id=[key(original.positions[a]),key(original.positions[b])].sort().join('|');const entry=edges.get(id);if(entry)entry.count++;else edges.set(id,{a,b,count:1});}
 const outer=new Map();function outerVertex(v){if(outer.has(v))return outer.get(v);const id=data.POSITION.length;for(const name of Object.keys(data))data[name].push(data[name][v].slice());outer.set(v,id);return id;}const inner=new Map();function add(v){if(inner.has(v))return inner.get(v);const id=data.POSITION.length;for(const name of Object.keys(data))data[name].push(data[name][v].slice());data.POSITION[id]=edit[si].positions[skin.get(key(original.positions[v]))].slice();inner.set(v,id);return id;}
 let added=0;for(const{a,b,count}of edges.values())if(count===1&&original.positions[a][1]<.80&&original.positions[b][1]<.80&&skin.has(key(original.positions[a]))&&skin.has(key(original.positions[b]))){const ia=add(a),ib=add(b);const oa=outerVertex(a),ob=outerVertex(b);for(const face of[[ob,oa,ia],[ob,ia,ib]]){const [pa,pb,pc]=face.map(v=>data.POSITION[v]),u=pb.map((x,k)=>x-pa[k]),v=pc.map((x,k)=>x-pa[k]);if(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])>2e-12){idx.push(...face);added++;}}}
 // Reuse the existing material and remove the now-redundant floating shorts trim.
 const bp=parts[bi],bp0=primitives[bi],bidx=read(bp.indices).flat(),kept=[];let removed=0;for(let n=0;n<bidx.length;n+=3){const face=bidx.slice(n,n+3);if(face.every(v=>bp0.positions[v][1]>.59&&bp0.positions[v][1]<.75&&Math.abs(bp0.positions[v][0])<.25))removed++;else kept.push(...face);}write(bp.indices,kept.map(v=>[v]));
 // Recompute welded area-weighted normals on the changed shorts, including hem.
 const sum=data.POSITION.map(()=>[0,0,0]);for(let n=0;n<idx.length;n+=3){const [a,b,c]=idx.slice(n,n+3),u=data.POSITION[b].map((x,k)=>x-data.POSITION[a][k]),v=data.POSITION[c].map((x,k)=>x-data.POSITION[a][k]),normal=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];for(const i of[a,b,c])for(let k=0;k<3;k++)sum[i][k]+=normal[k];}const welded=new Map();for(let i=0;i<sum.length;i++){const k=(i<original.positions.length?'outer:':'hem:')+key(data.POSITION[i]),v=welded.get(k)??[0,0,0];for(let j=0;j<3;j++)v[j]+=sum[i][j];welded.set(k,v);}data.NORMAL=sum.map((v,i)=>{v=welded.get((i<original.positions.length?'outer:':'hem:')+key(data.POSITION[i]));const l=Math.hypot(...v);return l?v.map(x=>x/l):data.NORMAL[i]});for(const[name,values]of Object.entries(data))write(p.attributes[name],values);write(p.indices,idx.map(v=>[v]));stats.hemBoundaryMap=[...inner].map(([sourceVertex,innerVertex])=>({sourceVertex,innerVertex,outerVertex:outer.get(sourceVertex),skinVertex:skin.get(key(original.positions[sourceVertex]))}));stats.hemTrianglesAdded=added;stats.obsoleteTrimTrianglesRemoved=removed;
 }
}
else await fs.writeFile(path.join(args.out,path.basename(args.source,'.glb')+'-mesh.json'),JSON.stringify(primitives));
const normalViews=new Set(doc.meshes.flatMap(m=>m.primitives.map(p=>doc.accessors[p.attributes.NORMAL].bufferView)));
const positionViews=new Set(doc.meshes.flatMap(m=>m.primitives.map(p=>doc.accessors[p.attributes.POSITION].bufferView)));
const finalRaw=new Map();stats.encodingMaxPositionErrorMm=0;stats.encodingMaxNormalComponentError=0;
function pack(compressed){const d=structuredClone(doc),chunks=[];let offset=0,fallback=0;for(let i=0;i<d.bufferViews.length;i++){const v=d.bufferViews[i],old=doc.bufferViews[i].extensions?.EXT_meshopt_compression;let payload;if(compressed&&old){const count=edited.has(i)?raw[i].length/old.byteStride:old.count;const normal=edited.has(i)&&normalViews.has(i),position=edited.has(i)&&positionViews.has(i),input=normal||position?MeshoptEncoder.encodeFilterExp(new Float32Array(raw[i].buffer,raw[i].byteOffset,raw[i].byteLength/4),count,old.byteStride,normal?12:18,'SharedComponent'):raw[i];payload=edited.has(i)?Buffer.from(MeshoptEncoder.encodeGltfBuffer(input,count,old.byteStride,old.mode)):bin.subarray(old.byteOffset,old.byteOffset+old.byteLength);if(edited.has(i)){const decoded=new Uint8Array(raw[i].length);MeshoptDecoder.decodeGltfBuffer(decoded,count,old.byteStride,payload,old.mode,normal||position?'EXPONENTIAL':'NONE');finalRaw.set(i,Buffer.from(decoded));if(normal||position){const before=new Float32Array(raw[i].buffer,raw[i].byteOffset,raw[i].byteLength/4),after=new Float32Array(decoded.buffer);let error=0;for(let n=0;n<before.length;n++)error=Math.max(error,Math.abs(before[n]-after[n]));if(position)stats.encodingMaxPositionErrorMm=Math.max(stats.encodingMaxPositionErrorMm,error*1000);else stats.encodingMaxNormalComponentError=Math.max(stats.encodingMaxNormalComponentError,error);}}v.extensions={EXT_meshopt_compression:{...old,buffer:0,byteOffset:offset,byteLength:payload.length,count,...(edited.has(i)?{filter:normal||position?'EXPONENTIAL':'NONE'}:{})}};v.buffer=1;v.byteOffset=fallback;fallback+=v.byteLength;}else{payload=finalRaw.get(i)??raw[i];v.buffer=0;v.byteOffset=offset;delete v.extensions;}chunks.push(payload);offset+=payload.length;const pad=(4-offset%4)%4;chunks.push(Buffer.alloc(pad));offset+=pad;}d.buffers=[{byteLength:offset},...(compressed?[{byteLength:fallback}]:[])];if(!compressed){d.extensionsUsed=d.extensionsUsed?.filter(x=>x!=='EXT_meshopt_compression');d.extensionsRequired=d.extensionsRequired?.filter(x=>x!=='EXT_meshopt_compression');}let j=Buffer.from(JSON.stringify(d));j=Buffer.concat([j,Buffer.alloc((4-j.length%4)%4,32)]);const binary=Buffer.concat(chunks),h=Buffer.alloc(20),bh=Buffer.alloc(8);h.write('glTF');h.writeUInt32LE(2,4);h.writeUInt32LE(28+j.length+binary.length,8);h.writeUInt32LE(j.length,12);h.write('JSON',16);bh.writeUInt32LE(binary.length);bh.write('BIN\0',4);return Buffer.concat([h,j,bh,binary]);}

const name=path.basename(args.source,'.glb'),candidate=pack(true);stats.bytes=candidate.length;stats.triangles=doc.meshes.flatMap(m=>m.primitives).reduce((n,p)=>n+doc.accessors[p.indices].count/3,0);if(stats.bytes>450000||stats.triangles>18000)throw Error('Budget exceeded');await fs.writeFile(path.join(args.out,name+'.glb'),candidate);await fs.writeFile(path.join(args.out,name+'-decoded.glb'),pack(false));await fs.writeFile(path.join(args.out,name+'-stats.json'),JSON.stringify(stats,null,2));console.log({...stats,hemBoundaryMap:stats.hemBoundaryMap?.length});
